[package]
name = "asset-agent-opcua"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
asset-agent-core = { path = "../asset-agent-core" }
async-opcua = { workspace = true, features = ["client", "server"] }
async-opcua-client.workspace = true
async-trait.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
